import path from 'path';
import fs from 'fs-extra';
import ora from 'ora';
import { copyModuleTemplate, writeFile, setTemplatesDir, getTemplatesDir } from './utils/file.js';
import { ensureTemplates } from './templates/manager.js';

// ─── Resolve template path ────────────────────────────────────────────────────

function resolveTemplatePath(config) {
  const TEMPLATES_DIR = getTemplatesDir();
  const { projectType, backendFramework, frontendFramework } = config;

  if (projectType === 'frontend') {
    return path.join(TEMPLATES_DIR, 'frontend', frontendFramework || 'static');
  }

  if (projectType === 'backend' || projectType === 'microservice' || projectType === 'worker') {
    const fw = backendFramework === 'nestjs' ? 'nest' : (backendFramework || 'express');
    if (fw === 'none') return null;
    return path.join(TEMPLATES_DIR, 'backend', fw);
  }

  return null; // fullstack, cli — handled separately
}

// ─── Generate .env.example ────────────────────────────────────────────────────

function buildEnvExample(config) {
  const lines = ['# Environment Variables', '# Copy to .env and fill in your values', ''];

  lines.push('NODE_ENV=development');
  lines.push('PORT=3000');
  lines.push('');

  if (config.database && config.database !== 'none') {
    const dbUrls = {
      postgresql: 'DATABASE_URL=postgresql://user:password@localhost:5432/dbname',
      mysql: 'DATABASE_URL=mysql://user:password@localhost:3306/dbname',
      mongodb: 'DATABASE_URL=mongodb://localhost:27017/dbname',
      sqlite: 'DATABASE_URL=file:./dev.db',
    };
    lines.push(dbUrls[config.database] || 'DATABASE_URL=');
    lines.push('');
  }

  if (config.auth === 'jwt') {
    lines.push('JWT_SECRET=your-secret-key-here');
    lines.push('JWT_EXPIRES_IN=7d');
    lines.push('');
  }

  if (config.auth === 'oauth') {
    lines.push('OAUTH_CLIENT_ID=');
    lines.push('OAUTH_CLIENT_SECRET=');
    lines.push('OAUTH_CALLBACK_URL=http://localhost:3000/auth/callback');
    lines.push('');
  }

  if (config.modules?.includes('redis') || config.modules?.includes('queue')) {
    lines.push('REDIS_URL=redis://localhost:6379');
    lines.push('');
  }

  if (config.modules?.includes('email')) {
    lines.push('SMTP_HOST=smtp.example.com');
    lines.push('SMTP_PORT=587');
    lines.push('SMTP_USER=');
    lines.push('SMTP_PASS=');
    lines.push('EMAIL_FROM=noreply@example.com');
    lines.push('');
  }

  if (config.modules?.includes('file-storage')) {
    lines.push('STORAGE_BUCKET=');
    lines.push('STORAGE_REGION=');
    lines.push('STORAGE_ACCESS_KEY=');
    lines.push('STORAGE_SECRET_KEY=');
    lines.push('');
  }

  const paymentVars = {
    stripe: ['STRIPE_SECRET_KEY=sk_test_...', 'STRIPE_WEBHOOK_SECRET=whsec_...'],
    paypal: ['PAYPAL_CLIENT_ID=', 'PAYPAL_CLIENT_SECRET='],
    paystack: ['PAYSTACK_SECRET_KEY=sk_test_...'],
    flutterwave: ['FLUTTERWAVE_SECRET_KEY=FLWSECK_TEST-...'],
  };

  if (config.payments && config.payments !== 'none' && paymentVars[config.payments]) {
    paymentVars[config.payments].forEach((v) => lines.push(v));
    lines.push('');
  }

  return lines.join('\n');
}

// ─── Generate README.md ───────────────────────────────────────────────────────

function buildReadme(config) {
  const lines = [];

  lines.push(`# ${config.projectName}`);
  lines.push('');
  lines.push('> Generated by [Launchstack](https://github.com/Ennygabby01/launchstack)');
  lines.push('');
  lines.push('## Stack');
  lines.push('');

  if (config.backendFramework && config.backendFramework !== 'none') {
    lines.push(`- **Backend:** ${config.backendFramework}`);
  }
  if (config.frontendFramework && config.frontendFramework !== 'none') {
    lines.push(`- **Frontend:** ${config.frontendFramework}`);
  }
  if (config.database && config.database !== 'none') {
    lines.push(`- **Database:** ${config.database}`);
  }
  if (config.orm && config.orm !== 'none') {
    lines.push(`- **ORM:** ${config.orm}`);
  }
  if (config.auth && config.auth !== 'none') {
    lines.push(`- **Auth:** ${config.auth.toUpperCase()}`);
  }
  if (config.modules?.length) {
    lines.push(`- **Modules:** ${config.modules.join(', ')}`);
  }
  if (config.payments && config.payments !== 'none') {
    lines.push(`- **Payments:** ${config.payments}`);
  }

  lines.push('');
  lines.push('## Getting Started');
  lines.push('');
  lines.push('```bash');
  lines.push('# Install dependencies');
  lines.push('npm install');
  lines.push('');
  lines.push('# Copy environment variables');
  lines.push('cp .env.example .env');
  lines.push('');
  lines.push('# Start development server');
  lines.push('npm run dev');
  lines.push('```');
  lines.push('');

  if (config.docker) {
    lines.push('## Docker');
    lines.push('');
    lines.push('```bash');
    lines.push('docker-compose up -d');
    lines.push('```');
    lines.push('');
  }

  lines.push('## License');
  lines.push('');
  lines.push('MIT');

  return lines.join('\n');
}

// ─── Generate Docker files ────────────────────────────────────────────────────

async function generateDockerFiles(config, projectPath) {
  const TEMPLATES_DIR = getTemplatesDir();
  const isPython = ['django', 'flask'].includes(config.backendFramework);
  const dockerTemplatePath = path.join(TEMPLATES_DIR, 'docker', isPython ? 'python' : 'node');

  if (await fs.pathExists(dockerTemplatePath)) {
    await fs.copy(dockerTemplatePath, projectPath, { overwrite: false });
  }

  await writeFile(path.join(projectPath, 'docker-compose.yml'), buildDockerCompose(config));
}

function buildDockerCompose(config) {
  const lines = ['version: "3.9"', '', 'services:'];

  lines.push('  app:');
  lines.push('    build: .');
  lines.push('    ports:');
  lines.push('      - "3000:3000"');
  lines.push('    environment:');
  lines.push('      - NODE_ENV=development');
  lines.push('    env_file:');
  lines.push('      - .env');
  lines.push('    depends_on:');

  const deps = [];
  if (config.database && config.database !== 'none') deps.push(config.database);
  if (config.modules?.includes('redis') || config.modules?.includes('queue')) deps.push('redis');

  if (deps.length) {
    deps.forEach((d) => lines.push(`      - ${d}`));
  } else {
    lines.push('      []');
  }

  lines.push('    volumes:');
  lines.push('      - .:/app');
  lines.push('      - /app/node_modules');

  if (config.database && config.database !== 'none') {
    lines.push('');
    switch (config.database) {
      case 'postgresql':
        lines.push('  postgresql:');
        lines.push('    image: postgres:17-alpine');
        lines.push('    environment:');
        lines.push('      POSTGRES_USER: user');
        lines.push('      POSTGRES_PASSWORD: password');
        lines.push('      POSTGRES_DB: dbname');
        lines.push('    ports:');
        lines.push('      - "5432:5432"');
        lines.push('    volumes:');
        lines.push('      - pgdata:/var/lib/postgresql/data');
        break;
      case 'mysql':
        lines.push('  mysql:');
        lines.push('    image: mysql:9');
        lines.push('    environment:');
        lines.push('      MYSQL_ROOT_PASSWORD: password');
        lines.push('      MYSQL_DATABASE: dbname');
        lines.push('      MYSQL_USER: user');
        lines.push('      MYSQL_PASSWORD: password');
        lines.push('    ports:');
        lines.push('      - "3306:3306"');
        lines.push('    volumes:');
        lines.push('      - mysqldata:/var/lib/mysql');
        break;
      case 'mongodb':
        lines.push('  mongodb:');
        lines.push('    image: mongo:8');
        lines.push('    ports:');
        lines.push('      - "27017:27017"');
        lines.push('    volumes:');
        lines.push('      - mongodata:/data/db');
        break;
    }
  }

  if (config.modules?.includes('redis') || config.modules?.includes('queue')) {
    lines.push('');
    lines.push('  redis:');
    lines.push('    image: redis:7-alpine');
    lines.push('    ports:');
    lines.push('      - "6379:6379"');
  }

  const volumes = [];
  if (config.database === 'postgresql') volumes.push('pgdata:');
  if (config.database === 'mysql') volumes.push('mysqldata:');
  if (config.database === 'mongodb') volumes.push('mongodata:');

  if (volumes.length) {
    lines.push('');
    lines.push('volumes:');
    volumes.forEach((v) => lines.push(`  ${v}`));
  }

  return lines.join('\n');
}

// ─── Generate .gitignore ──────────────────────────────────────────────────────

function buildGitignore(config) {
  const isPython = ['django', 'flask'].includes(config.backendFramework);

  const lines = [
    '# Dependencies',
    'node_modules/',
    '',
    '# Environment',
    '.env',
    '.env.local',
    '.env.*.local',
    '',
    '# Build output',
    'dist/',
    'build/',
    '.next/',
    '',
    '# Logs',
    'logs/',
    '*.log',
    '',
    '# OS',
    '.DS_Store',
    'Thumbs.db',
    '',
  ];

  if (isPython) {
    lines.push('# Python', '__pycache__/', '*.pyc', 'venv/', '.venv/', '');
  }

  if (config.orm === 'prisma') {
    lines.push('# Prisma', '*.db', '*.db-journal', '');
  }

  return lines.join('\n');
}

// ─── Generate launchstack.json manifest ───────────────────────────────────────

function buildManifest(config) {
  return JSON.stringify(
    {
      name: config.projectName,
      version: '1.0.0',
      launchstack: true,
      projectType: config.projectType,
      backendFramework: config.backendFramework || null,
      frontendFramework: config.frontendFramework || null,
      database: config.database || 'none',
      orm: config.orm || 'none',
      auth: config.auth || 'none',
      modules: config.modules || [],
      payments: config.payments || 'none',
      docker: config.docker || false,
      generatedAt: new Date().toISOString(),
    },
    null,
    2
  );
}

// ─── Main generate function ───────────────────────────────────────────────────

export async function generate(config) {
  const projectPath = path.join(process.cwd(), config.projectName);

  // Ensure templates are available before starting the main spinner
  // (ensureTemplates has its own spinner — avoid concurrent spinners)
  const templatesDir = await ensureTemplates();
  setTemplatesDir(templatesDir);

  const spinner = ora(`Creating project: ${config.projectName}`).start();

  try {
    await fs.ensureDir(projectPath);

    const TEMPLATES_DIR = getTemplatesDir();
    const templatePath = resolveTemplatePath(config);

    if (config.projectType === 'fullstack') {
      const bfw = config.backendFramework === 'nestjs' ? 'nest' : config.backendFramework;
      const backendTpl = path.join(TEMPLATES_DIR, 'backend', bfw || 'express');
      const frontendTpl = path.join(TEMPLATES_DIR, 'frontend', config.frontendFramework || 'react-vite');

      if (await fs.pathExists(backendTpl)) {
        await fs.copy(backendTpl, path.join(projectPath, 'backend'), { overwrite: false });
      }
      if (await fs.pathExists(frontendTpl)) {
        await fs.copy(frontendTpl, path.join(projectPath, 'frontend'), { overwrite: false });
      }
    } else if (templatePath && (await fs.pathExists(templatePath))) {
      await fs.copy(templatePath, projectPath, { overwrite: false });
    } else {
      await fs.ensureDir(path.join(projectPath, 'src'));
    }

    spinner.text = 'Injecting modules...';
    for (const mod of config.modules || []) {
      await copyModuleTemplate(mod, projectPath);
    }

    spinner.text = 'Generating config files...';
    await writeFile(path.join(projectPath, '.env.example'), buildEnvExample(config));
    await writeFile(path.join(projectPath, 'README.md'), buildReadme(config));
    await writeFile(path.join(projectPath, '.gitignore'), buildGitignore(config));
    await writeFile(path.join(projectPath, 'launchstack.json'), buildManifest(config));

    if (config.docker) {
      spinner.text = 'Generating Docker files...';
      await generateDockerFiles(config, projectPath);
    }

    spinner.succeed(`Project created at ./${config.projectName}`);
    return projectPath;
  } catch (err) {
    spinner.fail(`Failed to generate project: ${err.message}`);
    throw err;
  }
}

// ─── Add module to existing project ──────────────────────────────────────────

export async function addModule(moduleName, projectPath) {
  const manifestPath = path.join(projectPath, 'launchstack.json');

  if (!(await fs.pathExists(manifestPath))) {
    throw new Error('Not a launchstack project. Run launchstack init first.');
  }

  const spinner = ora(`Adding module: ${moduleName}`).start();

  try {
    await copyModuleTemplate(moduleName, projectPath);

    const manifest = await fs.readJson(manifestPath);
    if (!manifest.modules.includes(moduleName)) {
      manifest.modules.push(moduleName);
      await fs.writeJson(manifestPath, manifest, { spaces: 2 });
    }

    spinner.succeed(`Module "${moduleName}" added successfully`);
  } catch (err) {
    spinner.fail(`Failed to add module: ${err.message}`);
    throw err;
  }
}
